### PR TITLE
add loadBalancerKey when building a LoadBalancerCommand

### PR DESCRIPTION
**Pull request by lowzj**
I want to write a class implemented `IRule` to choose a service instance based on the `loadBalancerKey`, the 'IRule' implementation just like this:

```
public class MyLoadBalancerRule extends AbstractLoadBalancerRule {
    @Override
    public void initWithNiwsConfig(IClientConfig clientConfig) {
    }

    @Override
    public Server choose(Object key) {
        List<Server> servers = getLoadBalancer().getReachableServers();
        // choose and return a server from servers based on the key
    }
}
```

but the key is always `null`.

**LoadBalancerCommand** passes its attribute `loadBalancerKey` as parameter to the `choose` method. And **LoadBalancerCommand** object is constructed in `AbstractLoadBalancerAwareClient#executeWithLoadBalancer` without setting the attribute `loadBalancerKey`.

So I report this pr to add the `loadBalancerKey` when building a **LoadBalancerCommand** object.

### CODE REVIEW

**Comment by lowzj** [comment]
Is there anyone to take a look about this pr?

**Comment by qiangdavidliu** [comment]
@lowzj this seems like an oversight that you are fixing, however I am not familiar enough with logic here to be able to say whether this change may impact any existing assumed behaviour (whether the existing assumption is right or wrong).

Ribbon is currently in maintenance mode for us, which means that we may make changes/fixes that affect our internal usage, and also may be able to take a look at small, obvious PR requests from external contributors. However changes that can affect the existing "status quo" are something we want to avoid if possible.

I will try to point this PR to someone who remembers this code a bit better to see if they have any insight, but we can't promise anything.

**Comment by spencergibb** [comment]
Maybe it could be opt-in with a configuration setting so the default behaviour stays the same, but allows the option?

**Comment by lowzj** [comment]
@qiangdavidliu @spencergibb Maybe it's difficult to make a decision whether to merge this PR. And the `opt-in with a configuration setting` solution would lose efficacy when invoking `executeWithLoadBalancer(request)` or `executeWithLoadBalancer(request, null)`.

How about another solution: the class AbstractLoadBalancerAwareClient exposes a protected method `buildLoadBalancerCommand`. So It could stay the same behavior by using the default implementation, and at the same time it gives a chance to its derived classes to customize their own `LoadBalancerCommand`. The drawback is that we have to change its derived classes to override `buildLoadBalancerCommand` method .

**Comment by lowzj** [comment]
@spencergibb @qiangdavidliu There is nothing that affect the existing 'status quo', just give a change to its derived class to customize the `LoadBalancerCommand` object.

**Comment by lowzj** [comment]
@elandau  Could you please take a look at this PR? I'm eager for it to be merged.

**Comment by lowzj** [comment]
Is there anyone to take a look at this PR?

**Comment by csterwa** [comment]
@lowzj @spencergibb has there been any review of this PR?

**Comment by lowzj** [comment]
@csterwa I don't know, it seems no.

**Pull request merged**
